# Generated by Django 5.2.8 on 2026-03-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('new_matricule', models.CharField(max_length=50, unique=True)),
                ('ssn', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('blood_type', models.CharField(blank=True, choices=[('AP', 'AP'), ('AN', 'AN'), ('BP', 'BP'), ('BN', 'BN'), ('ABP', 'ABP'), ('ABN', 'ABN'), ('OP', 'OP'), ('ON', 'ON')], max_length=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
