# Generated by Django 5.2.8 on 2026-03-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='category',
            field=models.IntegerField(default=20),
        ),
    ]
